### ISSUE TITLE
Simplified Chinese is not supported.

### ISSUE THREAD

**Issue by changxinchang** [serifpersia/esp32partitiontool#13]
Simplified Chinese is not supported.
![arduino](https://github.com/user-attachments/assets/273281a2-8a96-470b-8638-e4ffd959ac30)

**Comment by serifpersia** [comment]
I verified the issue seems like other languages are also affected. This is due to using DejaVu font which should work fine I tested the same text using that font in Notepad and it displayed all text fine but it doesnt work in the tool. The immediate solution is to use built in fonts that display the text correctly instead. The following fonts work with these languages. 
Seems like re-saving the locale files as UTF-8 instead of UTF-8 with BOM didn't change anything still having issues with asian languages. For example Arabic works just fine. If unable to find fix using custom loaded font the feature will be removed and the ones below will be used since I verified that they show the text correctly at least for the text the form can still use the custom Dejavu font as it clearly looks better for the data entry.

```java
	public UI(JFrame frame, String title) {

		// Show tool tips immediately
		ToolTipManager.sharedInstance().setInitialDelay(0);

		defaultFont = new Font("Monospaced", Font.PLAIN, 12);
		monotypeFont = new Font("Monospaced", Font.PLAIN, 12);
		monotypeBoldFont = new Font("Monospaced", Font.BOLD, 12);
		condensedFont = new Font("Monospaced", Font.PLAIN, 12);

		setFrame(frame, title);
		setLayout(new BorderLayout(0, 0));
		setOpaque(false); // transparent background!
		init();
	}
```
![image](https://github.com/user-attachments/assets/7d22a6b1-b85c-4ab5-90e8-5e60f56a5c7a)

**Comment by changxinchang** [comment]
How to modify the downloaded ESP32PartitionTool.jar

**Comment by serifpersia** [comment]
> How to modify the downloaded ESP32PartitionTool.jar

There is nothing you can edit/modify in the jar its release binary, I will use different font and release new version you can download that later. Could you look into the translation files for your language and see if its correct so I can update that as well. You can find the translation files here. [english](https://github.com/serifpersia/esp32partitiontool/blob/main/src/main/resources/l10n/labels.properties) and [chinese](https://github.com/serifpersia/esp32partitiontool/blob/main/src/main/resources/l10n/labels_zh.properties)
If you feel like the translation is wrong please fork and do a PR with the changes to the chinese file.
EDIT: New font change was pushed. New 1.4.4 release has this new change. Use this latest version to get the fixed translated version of the text.
![image](https://github.com/user-attachments/assets/ea3bc581-d27f-4192-a704-d8ae0654c552)
